namespace Family.Vault.Application.Models;

/// <summary>
/// A single actionable insight generated by <c>IInsightService</c>.
/// </summary>
/// <param name="Title">Short human-readable title describing the gap or risk.</param>
/// <param name="Severity">How urgent the insight is.</param>
/// <param name="SuggestedAction">A concrete next step the user can take to resolve the insight.</param>
public sealed record InsightResponse(
    string Title,
    InsightSeverity Severity,
    string SuggestedAction);
