// <auto-generated />
using System;
using Family.Vault.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Family.Vault.Infrastructure.Database.Migrations
{
    [DbContext(typeof(FamilyVaultDbContext))]
    partial class FamilyVaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.AssetEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomineeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetType");

                    b.HasIndex("UserId");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.BankAccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountType")
                        .HasColumnType("TEXT");

                    b.Property<string>("IFSC_SWIFT")
                        .HasColumnType("TEXT");

                    b.Property<int>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nominee")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BankAccounts", (string)null);
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.ContactEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PriorityOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Relationship")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.DocumentMetadataEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.EmergencyFundEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessInstructions")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmergencyFunds", (string)null);
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.IndiaAssetEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Nominee")
                        .HasColumnType("TEXT");

                    b.Property<string>("Repatriation")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxStatus")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IndiaAssets", (string)null);
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.InsurancePolicyEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimContact")
                        .HasColumnType("TEXT");

                    b.Property<string>("Coverage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<double?>("CoverageAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nominee")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.ToTable("InsurancePolicies", (string)null);
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.InvestmentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CurrentValue")
                        .HasColumnType("REAL");

                    b.Property<string>("InvestmentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nominee")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Investments", (string)null);
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.NomineeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("ContactDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Nominees", (string)null);
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.ProfileEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChildrenJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpouseName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.PropertyEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentsLocation")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LoanLinked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnershipType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Properties", (string)null);
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.TaxEntryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeclaredInUK")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IncomeType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TaxPaid")
                        .HasColumnType("REAL");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TaxEntries", (string)null);
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.UkAssetEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nominee")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxNotes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UkAssets", (string)null);
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<int>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.WillEntryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutorName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExistsFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WillEntries", (string)null);
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.AssetEntity", b =>
                {
                    b.HasOne("Family.Vault.Infrastructure.Database.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.BankAccountEntity", b =>
                {
                    b.HasOne("Family.Vault.Infrastructure.Database.Entities.AssetEntity", null)
                        .WithOne()
                        .HasForeignKey("Family.Vault.Infrastructure.Database.Entities.BankAccountEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.ContactEntity", b =>
                {
                    b.HasOne("Family.Vault.Infrastructure.Database.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.DocumentMetadataEntity", b =>
                {
                    b.HasOne("Family.Vault.Infrastructure.Database.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.EmergencyFundEntity", b =>
                {
                    b.HasOne("Family.Vault.Infrastructure.Database.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.IndiaAssetEntity", b =>
                {
                    b.HasOne("Family.Vault.Infrastructure.Database.Entities.AssetEntity", null)
                        .WithOne()
                        .HasForeignKey("Family.Vault.Infrastructure.Database.Entities.IndiaAssetEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.InsurancePolicyEntity", b =>
                {
                    b.HasOne("Family.Vault.Infrastructure.Database.Entities.AssetEntity", null)
                        .WithOne()
                        .HasForeignKey("Family.Vault.Infrastructure.Database.Entities.InsurancePolicyEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.InvestmentEntity", b =>
                {
                    b.HasOne("Family.Vault.Infrastructure.Database.Entities.AssetEntity", null)
                        .WithOne()
                        .HasForeignKey("Family.Vault.Infrastructure.Database.Entities.InvestmentEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.NomineeEntity", b =>
                {
                    b.HasOne("Family.Vault.Infrastructure.Database.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.ProfileEntity", b =>
                {
                    b.HasOne("Family.Vault.Infrastructure.Database.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.PropertyEntity", b =>
                {
                    b.HasOne("Family.Vault.Infrastructure.Database.Entities.AssetEntity", null)
                        .WithOne()
                        .HasForeignKey("Family.Vault.Infrastructure.Database.Entities.PropertyEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.TaxEntryEntity", b =>
                {
                    b.HasOne("Family.Vault.Infrastructure.Database.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.UkAssetEntity", b =>
                {
                    b.HasOne("Family.Vault.Infrastructure.Database.Entities.AssetEntity", null)
                        .WithOne()
                        .HasForeignKey("Family.Vault.Infrastructure.Database.Entities.UkAssetEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Family.Vault.Infrastructure.Database.Entities.WillEntryEntity", b =>
                {
                    b.HasOne("Family.Vault.Infrastructure.Database.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
