@Family.Vault.API_HostAddress = http://localhost:5102

GET {{Family.Vault.API_HostAddress}}/api/vault
Accept: application/json

###

GET {{Family.Vault.API_HostAddress}}/api/vault/download/sample.txt
Accept: application/octet-stream

###

POST {{Family.Vault.API_HostAddress}}/api/vault/upload
Content-Type: multipart/form-data; boundary=FamilyVaultBoundary

--FamilyVaultBoundary
Content-Disposition: form-data; name="file"; filename="sample.txt"
Content-Type: text/plain

sample-content
--FamilyVaultBoundary--

###
